### ISSUE TITLE
How to handle Submit click when no data is entered.

### ISSUE THREAD

**Issue by vrajendraBhavsar** [benjamin-luescher/compose-form#6]
Hey, firstly thanks a bunch for creating such easy to use form! I have one query regarding a case where a button is pressed when no data is entered. In current implementation no error is being shown or literally nothing is happening. So how can I handle such case in existing implementation. 

P.S - I think when no data is entered then all the fields should show an error on a button click.

**Comment by benjamin-luescher** [comment]
Hi @vrajendraBhavsar. Thank you!
Please make sure to call `form.validate(ignoreUntouched = false)` instead of `form.validate(ignoreUntouched = true)` in your scenario.

You'll find snippets below for your scenario.
```
@HiltViewModel
class MainViewModel @Inject constructor(
    resourcesProvider: ResourcesProvider
): ViewModel() {
    var form = MainForm(resourcesProvider)
    
    // ...

    fun validate() {
        form.validate() // <--- call  `form.validate(true)` if you want to validate by ignoring untouched fields 
        Log.d("MainViewModel", "Validate (form is valid: ${form.isValid})")
    }
}
```
You can call this function from the `onClick` callback of your button: 
```
@Composable
fun FormPage() {
    val viewModel = hiltViewModel<MainViewModel>()
    // your form
    // ...
    
    // submit button - call validate function on viewModel to validate form
    Button(onClick = viewModel::validate)
}
```

**Comment by vrajendraBhavsar** [comment]
Hey @benjamin-luescher gracias for providing the solution!
